name: pudl-usage-metrics
channels:
  - conda-forge
  - defaults
dependencies:
  # Used to set up the environment
  - pip>=21,<23
  - python>=3.10,<3.11
  - setuptools<62
  - pre-commit~=2.9
  - jupyter_contrib_nbextensions~=0.5
  - pip:
      - --editable ./[doc,test,dev]
