name: business-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # Used to set up the environment
  - pip>=21,<23
  - python>=3.8,<3.11
  - setuptools<62
  - pre-commit~=2.9
  - pip:
      - --editable ./usage_metrics/[doc,test,dev]
