[project]
name = "pudl_usage_metrics"
version = "0.1.0"
authors = [{name = "PUDL", email = "pudl@catalyst.coop"}]
requires-python = ">=3.14,<3.15"

# managed by pixi; see tool.pixi.dependencies below
# cloud-sql-python-connector is configured here because we need extras [pg8000].
dependencies = [
    "cloud-sql-python-connector[pg8000]>=1.11.0",
]

[project.scripts]
pudl_usage_metrics = "pudl_usage_metrics.cli:main"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
packages = ["src/usage_metrics"]

[tool.pixi.workspace]
name = "pudl-usage-metrics"
platforms = ["linux-64", "osx-64", "osx-arm64"]
channels = ["conda-forge"]

[tool.pixi.environments]
default = ["default"]
test = ["test"]

[tool.pixi.dependencies]
pandas = ">=3"
sqlalchemy = ">=2"
dagster = ">=1.13"
dagster-webserver = ">=1.13"
pandas-gbq = ">=0.23.1"
pydata-google-auth = ">=1.8.2"
jupyterlab = ">=4.2.3"
psycopg2-binary = ">=2.9.9"
joblib = ">=1.4.2"
matplotlib = ">=3.9.0"
pg8000 = ">=1.31.1"
google-cloud-storage = ">=2.17"
kaggle = ">=1.6.3"
s3fs = ">=2025.10.0"
polars = ">=1.43.2"
google-cloud-sdk = ">=580"

[tool.pixi.pypi-dependencies]
# Install the local package in editable mode. Assume dependencies are specified either
# above in [tools.pixi.dependencies] (for conda packages) or in this section, if they
# happen to only be available via PyPI.
pudl-usage-metrics = { path = ".", editable = true }
ipinfo = ">=5.0.1"

[tool.pixi.feature.test.dependencies]
pytest = ">=9"
coverage = ">=7"
doc8 = ">=2"
prek = ">=0.4.13"
pydocstyle = ">=6.3"
pytest-asyncio = ">=1.4"
pytest-console-scripts = ">=1.4.1"
pytest-cov = ">=7"
pytest-mock = ">=3.15"
ruff = ">=0.16"

[tool.pixi.tasks.update-local]
cmd = "dagster dev -m usage_metrics.etl"
env = { METRICS_PROD_ENV = "local" }
description = "Start dagster server that stores ETL results locally"

[tool.pixi.tasks.update-prod]
cmd = "dagster dev -m usage_metrics.etl"
env = { METRICS_PROD_ENV = "prod" }
description = "Start dagster server that stores ETL results in GCS"

[tool.pixi.feature.test.tasks.ruff-check]
cmd = "ruff check ./"
description = "Run the ruff linter on the whole repo"

[tool.pixi.feature.test.tasks.prek-run]
cmd = "prek run --all-files --show-diff-on-failure"
description = "Run all pre-commit hooks"

[tool.pixi.feature.test.tasks.linters]
depends-on = [
    "prek-run",
    "ruff-check"
]
description = "Run the pre-commit hooks and ruff linters"

[tool.pixi.feature.test.tasks.coverage-erase]
cmd = "coverage erase"
description = "Clear coverage data"

[tool.pixi.feature.test.tasks.pytest-unit]
cmd = "pytest --cov=src/usage_metrics --cov-append --cov-report=xml --doctest-modules src/usage_metrics tests"
description = "Run all the software unit tests"

[tool.pixi.feature.test.tasks.pytest-ci]
cmd = "coverage report --sort=cover"
depends-on = [
    "coverage-erase",
    "linters",
    "pytest-unit",
]
description = "Run all CI tests and report test coverage"

[tool.doc8]
max-line-length = 88
ignore-path = ["docs/_build"]

[tool.pytest.ini_options]
testpaths = "./"
filterwarnings = [
    "ignore:distutils Version classes are deprecated:DeprecationWarning",
    "ignore:Creating a LegacyVersion:DeprecationWarning:pkg_resources[.*]",
]
addopts = "--verbose"
log_format = "%(asctime)s [%(levelname)8s] %(name)s:%(lineno)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
log_cli = "true"
log_cli_level = "INFO"
doctest_optionflags = [
    "NORMALIZE_WHITESPACE",
    "IGNORE_EXCEPTION_DETAIL",
    "ELLIPSIS",
]

[tool.ruff]
# Assume Python 3.12
target-version = "py314"
line-length = 88
indent-width = 4
exclude = ["migrations/versions", "*.ipynb"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
extend-select = [
    "A", # flake8-builtins
    # "ARG", # unused arguments
    # "B",  # flake8-bugbear
    "C",   # Limit cyclomatic complexity using mccabe
    "D",   # pydocstyle errors
    "E",   # pycodestyle errors
    "EXE", # executable file issues
    # "ERA", # eradicate: find commented out code
    "F",   # pyflakes
    "I",   # isort
    "ISC", # implicit string concatenation
    "N",   # pep8-naming
    "NPY", # NumPy specific checks
    "PD",  # pandas checks
    "PGH", # pygrep-hooks
    # "PL",  # pylint
    # "PT",  # pytest style
    "PTH", # use pathlib
    "Q",   # flake8-quotes
    "RET", # check return values
    "RSE", # unnecessary parenthises on raised exceptions
    "S",   # flake8-bandit
    "SIM", # flake8-simplify
    # "T",   # print statements found
    "UP", # pyupgrade (use modern python syntax)
    "W",  # pycodestyle warnings
]

ignore = [
    "D401",   # Require imperative mood in docstrings.
    "D417",
    "E501",   # Overlong lines.
    "E203",   # Space before ':' (black recommends to ignore)
    "PD003",  # Use of isna rather than isnull
    "PD004",  # Use of notna rather than notnull
    "PD008",  # Use of df.at[] rather than df.loc[]
    "PD010",  # Use of df.stack()
    "PD013",  # Use of df.unstack()
    "PD015",  # Use of pd.merge() rather than df.merge()
    "RET504", # Ignore unnecessary assignment before return
    "S101",   # Use of assert
]

# Don't automatically concatenate strings -- sometimes we forget a comma!
unfixable = ["ISC"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]    # Ignore unused imports
"tests/*" = ["D"]

[tool.ruff.lint.pep8-naming]
# Allow Pydantic's `@validator` decorator to trigger class method treatment.
classmethod-decorators = ["pydantic.validator", "pydantic.root_validator"]

[tool.ruff.lint.isort]
known-first-party = ["ferc_xbrl_extractor"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"
