"""Add core kaggle table

Revision ID: 0d362f2deb28
Revises: 23e83521c288
Create Date: 2024-09-16 16:32:22.400482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d362f2deb28'
down_revision: Union[str, None] = '23e83521c288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_kaggle_logs',
    sa.Column('metrics_date', sa.DateTime(), nullable=False, comment='The unique date for each metrics snapshot.'),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('total_downloads', sa.Integer(), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=True),
    sa.Column('usability_rating', sa.Float(), nullable=True),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('is_private', sa.String(), nullable=True),
    sa.Column('licenses', sa.String(), nullable=True),
    sa.Column('collaborators', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('partition_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('metrics_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_kaggle_logs')
    # ### end Alembic commands ###
