"""test

Revision ID: 0fb2e639d75b
Revises:
Create Date: 2024-09-10 14:11:38.540862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb2e639d75b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_s3_logs',
    sa.Column('request_id', sa.String(), nullable=False, comment='A unique ID for each log.'),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('request_uri', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('bucket', sa.String(), nullable=True),
    sa.Column('bucket_owner', sa.String(), nullable=True),
    sa.Column('requester', sa.String(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('megabytes_sent', sa.Float(), nullable=True),
    sa.Column('remote_ip', sa.String(), nullable=True),
    sa.Column('remote_ip_city', sa.String(), nullable=True),
    sa.Column('remote_ip_loc', sa.String(), nullable=True),
    sa.Column('remote_ip_org', sa.String(), nullable=True),
    sa.Column('remote_ip_hostname', sa.String(), nullable=True),
    sa.Column('remote_ip_country_name', sa.String(), nullable=True),
    sa.Column('remote_ip_asn', sa.String(), nullable=True),
    sa.Column('remote_ip_country', sa.String(), nullable=True),
    sa.Column('remote_ip_timezone', sa.String(), nullable=True),
    sa.Column('remote_ip_latitude', sa.Float(), nullable=True),
    sa.Column('remote_ip_longitude', sa.Float(), nullable=True),
    sa.Column('remote_ip_postal', sa.String(), nullable=True),
    sa.Column('remote_ip_region', sa.String(), nullable=True),
    sa.Column('remote_ip_full_location', sa.String(), nullable=True),
    sa.Column('access_point_arn', sa.String(), nullable=True),
    sa.Column('acl_required', sa.String(), nullable=True),
    sa.Column('authentication_type', sa.String(), nullable=True),
    sa.Column('cipher_suite', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('host_header', sa.String(), nullable=True),
    sa.Column('host_id', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('object_size', sa.Float(), nullable=True),
    sa.Column('referer', sa.String(), nullable=True),
    sa.Column('signature_version', sa.String(), nullable=True),
    sa.Column('tls_version', sa.String(), nullable=True),
    sa.Column('total_time', sa.BigInteger(), nullable=True),
    sa.Column('turn_around_time', sa.Float(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('version_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('datasette_request_logs',
    sa.Column('insert_id', sa.String(), nullable=False, comment='A unique ID for each log.'),
    sa.Column('log_name', sa.String(), nullable=True),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('text_payload', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('receive_timestamp', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('http_request', sa.String(), nullable=True),
    sa.Column('labels', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('trace', sa.String(), nullable=True),
    sa.Column('span_id', sa.String(), nullable=True),
    sa.Column('trace_sampled', sa.Boolean(), nullable=True),
    sa.Column('source_location', sa.String(), nullable=True),
    sa.Column('cache_hit', sa.String(), nullable=True),
    sa.Column('cache_lookup', sa.String(), nullable=True),
    sa.Column('request_url', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('cache_fill_bytes', sa.String(), nullable=True),
    sa.Column('response_size', sa.Float(), nullable=True),
    sa.Column('server_ip', sa.String(), nullable=True),
    sa.Column('cache_validated_with_origin_server', sa.String(), nullable=True),
    sa.Column('request_method', sa.String(), nullable=True),
    sa.Column('request_size', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('referer', sa.String(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('remote_ip', sa.String(), nullable=True),
    sa.Column('request_url_path', sa.String(), nullable=True),
    sa.Column('request_url_query', sa.String(), nullable=True),
    sa.Column('request_url_scheme', sa.String(), nullable=True),
    sa.Column('request_url_netloc', sa.String(), nullable=True),
    sa.Column('remote_ip_city', sa.String(), nullable=True),
    sa.Column('remote_ip_loc', sa.String(), nullable=True),
    sa.Column('remote_ip_org', sa.String(), nullable=True),
    sa.Column('remote_ip_hostname', sa.String(), nullable=True),
    sa.Column('remote_ip_country_name', sa.String(), nullable=True),
    sa.Column('remote_ip_asn', sa.String(), nullable=True),
    sa.Column('remote_ip_country', sa.String(), nullable=True),
    sa.Column('remote_ip_timezone', sa.String(), nullable=True),
    sa.Column('remote_ip_latitude', sa.Float(), nullable=True),
    sa.Column('remote_ip_longitude', sa.Float(), nullable=True),
    sa.Column('remote_ip_postal', sa.String(), nullable=True),
    sa.Column('remote_ip_region', sa.String(), nullable=True),
    sa.Column('remote_ip_full_location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('insert_id')
    )
    op.create_table('intake_logs',
    sa.Column('insert_id', sa.String(), nullable=False, comment='A unique ID for each log.'),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('remote_ip', sa.String(), nullable=True),
    sa.Column('request_method', sa.String(), nullable=True),
    sa.Column('request_uri', sa.String(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('request_bytes', sa.BigInteger(), nullable=True),
    sa.Column('response_bytes', sa.BigInteger(), nullable=True),
    sa.Column('response_time_taken', sa.BigInteger(), nullable=True),
    sa.Column('request_host', sa.String(), nullable=True),
    sa.Column('request_referer', sa.String(), nullable=True),
    sa.Column('request_user_agent', sa.String(), nullable=True),
    sa.Column('request_operation', sa.String(), nullable=True),
    sa.Column('request_bucket', sa.String(), nullable=True),
    sa.Column('request_object', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('object_path', sa.String(), nullable=True),
    sa.Column('remote_ip_type', sa.String(), nullable=True),
    sa.Column('remote_ip_city', sa.String(), nullable=True),
    sa.Column('remote_ip_loc', sa.String(), nullable=True),
    sa.Column('remote_ip_org', sa.String(), nullable=True),
    sa.Column('remote_ip_hostname', sa.String(), nullable=True),
    sa.Column('remote_ip_country_name', sa.String(), nullable=True),
    sa.Column('remote_ip_asn', sa.String(), nullable=True),
    sa.Column('remote_ip_country', sa.String(), nullable=True),
    sa.Column('remote_ip_timezone', sa.String(), nullable=True),
    sa.Column('remote_ip_latitude', sa.Float(), nullable=True),
    sa.Column('remote_ip_longitude', sa.Float(), nullable=True),
    sa.Column('remote_ip_postal', sa.String(), nullable=True),
    sa.Column('remote_ip_region', sa.String(), nullable=True),
    sa.Column('remote_ip_full_location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('insert_id')
    )
    op.create_table('out_s3_logs',
    sa.Column('request_id', sa.String(), nullable=False, comment='A unique ID for each log.'),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('table', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('remote_ip', sa.String(), nullable=True),
    sa.Column('remote_ip_city', sa.String(), nullable=True),
    sa.Column('remote_ip_loc', sa.String(), nullable=True),
    sa.Column('remote_ip_org', sa.String(), nullable=True),
    sa.Column('remote_ip_hostname', sa.String(), nullable=True),
    sa.Column('remote_ip_country_name', sa.String(), nullable=True),
    sa.Column('remote_ip_asn', sa.String(), nullable=True),
    sa.Column('remote_ip_country', sa.String(), nullable=True),
    sa.Column('remote_ip_timezone', sa.String(), nullable=True),
    sa.Column('remote_ip_latitude', sa.Float(), nullable=True),
    sa.Column('remote_ip_longitude', sa.Float(), nullable=True),
    sa.Column('remote_ip_postal', sa.String(), nullable=True),
    sa.Column('remote_ip_region', sa.String(), nullable=True),
    sa.Column('remote_ip_full_location', sa.String(), nullable=True),
    sa.Column('access_point_arn', sa.String(), nullable=True),
    sa.Column('acl_required', sa.String(), nullable=True),
    sa.Column('authentication_type', sa.String(), nullable=True),
    sa.Column('megabytes_sent', sa.Float(), nullable=True),
    sa.Column('cipher_suite', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('host_header', sa.String(), nullable=True),
    sa.Column('host_id', sa.String(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('object_size', sa.Float(), nullable=True),
    sa.Column('referer', sa.String(), nullable=True),
    sa.Column('request_uri', sa.String(), nullable=True),
    sa.Column('signature_version', sa.String(), nullable=True),
    sa.Column('tls_version', sa.String(), nullable=True),
    sa.Column('total_time', sa.BigInteger(), nullable=True),
    sa.Column('turn_around_time', sa.Float(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('version_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('out_s3_logs')
    op.drop_table('intake_logs')
    op.drop_table('datasette_request_logs')
    op.drop_table('core_s3_logs')
    # ### end Alembic commands ###
