"""Add normalized downloads and categorize S3 use type

Revision ID: 125d095ac7e2
Revises: 18aca676b08b
Create Date: 2025-12-11 15:35:03.348096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '125d095ac7e2'
down_revision: Union[str, None] = '18aca676b08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_s3_logs', sa.Column('normalized_file_downloads', sa.Float(), nullable=True, comment='The proportion of the file that is downloaded (0 to 1).'))
    op.add_column('out_s3_logs', sa.Column('usage_type', sa.String(), nullable=True, comment='The type of usage activity. Distinguishes between requests made through DuckDB via the eel hole (eel_hole_duckdb), by clicking the download Parquet button in the eel hole (eel_hole_link), by clicking a download link from the docs, or other direct S3 activity.'))
    op.add_column('out_s3_logs', sa.Column('normalized_file_downloads', sa.Float(), nullable=True, comment='The proportion of the file that is downloaded (0 to 1).'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('out_s3_logs', 'normalized_file_downloads')
    op.drop_column('out_s3_logs', 'usage_type')
    op.drop_column('core_s3_logs', 'normalized_file_downloads')
    # ### end Alembic commands ###
