"""Add my cool new user_domain column

Revision ID: 18aca676b08b
Revises: a9524eefb534
Create Date: 2025-12-11 11:38:56.113461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18aca676b08b'
down_revision: Union[str, None] = 'a9524eefb534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_eel_hole_downloads', sa.Column('user_domain', sa.String(), nullable=True, comment="User's email domain - the part of a user's email address that follows the '@' symbol."))
    op.add_column('core_eel_hole_previews', sa.Column('user_domain', sa.String(), nullable=True, comment="User's email domain - the part of a user's email address that follows the '@' symbol."))
    op.add_column('core_eel_hole_searches', sa.Column('user_domain', sa.String(), nullable=True, comment="User's email domain - the part of a user's email address that follows the '@' symbol."))
    op.add_column('core_eel_hole_user_settings_updates', sa.Column('user_domain', sa.String(), nullable=True, comment="User's email domain - the part of a user's email address that follows the '@' symbol."))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_eel_hole_user_settings_updates', 'user_domain')
    op.drop_column('core_eel_hole_searches', 'user_domain')
    op.drop_column('core_eel_hole_previews', 'user_domain')
    op.drop_column('core_eel_hole_downloads', 'user_domain')
    # ### end Alembic commands ###
