"""Add core github tables

Revision ID: 764314d4f278
Revises: 0d362f2deb28
Create Date: 2024-09-19 17:35:16.372780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764314d4f278'
down_revision: Union[str, None] = '0d362f2deb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_github_clones',
    sa.Column('metrics_date', sa.DateTime(), nullable=False, comment='The date for each metrics snapshot.'),
    sa.Column('total_clones', sa.Integer(), nullable=True),
    sa.Column('unique_clones', sa.Integer(), nullable=True),
    sa.Column('partition_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('metrics_date')
    )
    op.create_table('core_github_forks',
    sa.Column('id', sa.Integer(), nullable=False, comment='The unique identifier for each fork.'),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('size_kb', sa.Integer(), nullable=True),
    sa.Column('stargazers_count', sa.Integer(), nullable=True),
    sa.Column('watchers_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('has_issues', sa.Boolean(), nullable=True),
    sa.Column('has_projects', sa.Boolean(), nullable=True),
    sa.Column('has_downloads', sa.Boolean(), nullable=True),
    sa.Column('has_wiki', sa.Boolean(), nullable=True),
    sa.Column('has_pages', sa.Boolean(), nullable=True),
    sa.Column('has_discussions', sa.Boolean(), nullable=True),
    sa.Column('forks_count', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('allow_forking', sa.Boolean(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('web_commit_signoff_required', sa.Boolean(), nullable=True),
    sa.Column('topics', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('open_issues', sa.Integer(), nullable=True),
    sa.Column('watchers', sa.Integer(), nullable=True),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('permissions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_github_popular_paths',
    sa.Column('metrics_date', sa.DateTime(), nullable=False, comment='The date for each metrics snapshot.'),
    sa.Column('path', sa.String(), nullable=False, comment='One of the ten most popular Github paths on a given date.'),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('unique_views', sa.Integer(), nullable=True),
    sa.Column('partition_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('metrics_date', 'path')
    )
    op.create_table('core_github_popular_referrers',
    sa.Column('metrics_date', sa.DateTime(), nullable=False, comment='The date for each metrics snapshot.'),
    sa.Column('referrer', sa.String(), nullable=False, comment='The unique referrer.'),
    sa.Column('total_referrals', sa.Integer(), nullable=True),
    sa.Column('unique_referrals', sa.Integer(), nullable=True),
    sa.Column('partition_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('metrics_date', 'referrer')
    )
    op.create_table('core_github_stargazers',
    sa.Column('id', sa.Integer(), nullable=False, comment='The unique identifier for each stargazer.'),
    sa.Column('starred_at', sa.DateTime(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('html_url', sa.String(), nullable=True),
    sa.Column('followers_url', sa.String(), nullable=True),
    sa.Column('following_url', sa.String(), nullable=True),
    sa.Column('gists_url', sa.String(), nullable=True),
    sa.Column('starred_url', sa.String(), nullable=True),
    sa.Column('subscriptions_url', sa.String(), nullable=True),
    sa.Column('organizations_url', sa.String(), nullable=True),
    sa.Column('repos_url', sa.String(), nullable=True),
    sa.Column('events_url', sa.String(), nullable=True),
    sa.Column('received_events_url', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('site_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_github_views',
    sa.Column('metrics_date', sa.DateTime(), nullable=False, comment='The date for each metrics snapshot.'),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('unique_views', sa.Integer(), nullable=True),
    sa.Column('partition_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('metrics_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_github_views')
    op.drop_table('core_github_stargazers')
    op.drop_table('core_github_popular_referrers')
    op.drop_table('core_github_popular_paths')
    op.drop_table('core_github_forks')
    op.drop_table('core_github_clones')
    # ### end Alembic commands ###
