"""Add pull requests to github forks table

Revision ID: a7d9118e9b0d
Revises: 125d095ac7e2
Create Date: 2026-03-18 15:39:21.669983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d9118e9b0d'
down_revision: Union[str, None] = '125d095ac7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_github_forks', sa.Column('has_pull_requests', sa.Boolean(), nullable=True, comment='Does the repository have pull requests?'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_github_forks', 'has_pull_requests')
    # ### end Alembic commands ###
