"""Add sixth filter field

Revision ID: a9524eefb534
Revises: c5dad3be2148
Create Date: 2025-10-16 08:57:34.088331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9524eefb534'
down_revision: Union[str, None] = 'c5dad3be2148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_eel_hole_downloads', sa.Column('params_filters_field_name_6', sa.String(), nullable=True, comment='The variable on which a user is performing a filter using DuckDB.'))
    op.add_column('core_eel_hole_downloads', sa.Column('params_filters_field_type_6', sa.String(), nullable=True, comment='The data type of the variable on which a user is performing a filter using DuckDB.'))
    op.add_column('core_eel_hole_downloads', sa.Column('params_filters_operation_6', sa.String(), nullable=True, comment='The operation performed on the variable a user is using to perform a filter using DuckDB (e.g., greater than, contains).'))
    op.add_column('core_eel_hole_downloads', sa.Column('params_filters_value_6', sa.String(), nullable=True, comment="The value that a user is using to perform a filter using DuckDB (e.g., greater than 2017, contains 'natural gas')."))
    op.add_column('core_eel_hole_previews', sa.Column('params_filters_field_name_6', sa.String(), nullable=True, comment='The variable on which a user is performing a filter using DuckDB.'))
    op.add_column('core_eel_hole_previews', sa.Column('params_filters_field_type_6', sa.String(), nullable=True, comment='The data type of the variable on which a user is performing a filter using DuckDB.'))
    op.add_column('core_eel_hole_previews', sa.Column('params_filters_operation_6', sa.String(), nullable=True, comment='The operation performed on the variable a user is using to perform a filter using DuckDB (e.g., greater than, contains).'))
    op.add_column('core_eel_hole_previews', sa.Column('params_filters_value_6', sa.String(), nullable=True, comment="The value that a user is using to perform a filter using DuckDB (e.g., greater than 2017, contains 'natural gas')."))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_eel_hole_previews', 'params_filters_value_6')
    op.drop_column('core_eel_hole_previews', 'params_filters_operation_6')
    op.drop_column('core_eel_hole_previews', 'params_filters_field_type_6')
    op.drop_column('core_eel_hole_previews', 'params_filters_field_name_6')
    op.drop_column('core_eel_hole_downloads', 'params_filters_value_6')
    op.drop_column('core_eel_hole_downloads', 'params_filters_operation_6')
    op.drop_column('core_eel_hole_downloads', 'params_filters_field_type_6')
    op.drop_column('core_eel_hole_downloads', 'params_filters_field_name_6')
    # ### end Alembic commands ###
