"""Add session_id to core eel hole tables, drop user_id from log_ins

Revision ID: bb5b305691a3
Revises: f3ce52f756e0
Create Date: 2025-09-08 17:48:25.792000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5b305691a3'
down_revision: Union[str, None] = 'f3ce52f756e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_eel_hole_downloads', sa.Column('session_id', sa.Float(), nullable=True, comment='A session ID for a logged in user. A new session is created after a user has been inactive for 30 minutes.'))
    op.add_column('core_eel_hole_hits', sa.Column('session_id', sa.Float(), nullable=True, comment='A session ID for a logged in user. A new session is created after a user has been inactive for 30 minutes.'))
    op.add_column('core_eel_hole_log_ins', sa.Column('session_id', sa.Float(), nullable=True, comment='A session ID for a logged in user. A new session is created after a user has been inactive for 30 minutes.'))
    op.add_column('core_eel_hole_previews', sa.Column('session_id', sa.Float(), nullable=True, comment='A session ID for a logged in user. A new session is created after a user has been inactive for 30 minutes.'))
    op.add_column('core_eel_hole_searches', sa.Column('session_id', sa.Float(), nullable=True, comment='A session ID for a logged in user. A new session is created after a user has been inactive for 30 minutes.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_eel_hole_searches', 'session_id')
    op.drop_column('core_eel_hole_previews', 'session_id')
    op.drop_column('core_eel_hole_log_ins', 'session_id')
    op.drop_column('core_eel_hole_hits', 'session_id')
    op.drop_column('core_eel_hole_downloads', 'session_id')
    # ### end Alembic commands ###
