"""Add partition_key column

Revision ID: f127226cf7df
Revises: 0fb2e639d75b
Create Date: 2024-09-11 11:07:58.530929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f127226cf7df'
down_revision: Union[str, None] = '0fb2e639d75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_s3_logs', sa.Column('partition_key', sa.String(), nullable=True))
    op.add_column('datasette_request_logs', sa.Column('partition_key', sa.String(), nullable=True))
    op.add_column('intake_logs', sa.Column('partition_key', sa.String(), nullable=True))
    op.add_column('out_s3_logs', sa.Column('partition_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('out_s3_logs', 'partition_key')
    op.drop_column('intake_logs', 'partition_key')
    op.drop_column('datasette_request_logs', 'partition_key')
    op.drop_column('core_s3_logs', 'partition_key')
    # ### end Alembic commands ###
