"""update eel hole tables with user ID info

Revision ID: f3ce52f756e0
Revises: 8bef33036a50
Create Date: 2025-09-08 15:44:28.868153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ce52f756e0'
down_revision: Union[str, None] = '8bef33036a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_eel_hole_user_settings_updates',
    sa.Column('insert_id', sa.String(), nullable=False, comment='A unique identifier for the log entry.'),
    sa.Column('user_id', sa.String(), nullable=True, comment="The unique ID identifying a logged-in user's activity. Implemented 09-2025."),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='The time the event described by the log entry occurred.'),
    sa.Column('accepted', sa.Boolean(), nullable=True, comment='Has a user accepted the privacy policy?'),
    sa.Column('newsletter', sa.Boolean(), nullable=True, comment='Has a user subscribed to the newsletter?'),
    sa.Column('outreach', sa.Boolean(), nullable=True, comment='Has a user agreed to be contacted for further discussion about PUDL?'),
    sa.Column('partition_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('insert_id')
    )
    op.add_column('core_eel_hole_downloads', sa.Column('user_id', sa.String(), nullable=True, comment="The unique ID identifying a logged-in user's activity. Implemented 09-2025."))
    op.add_column('core_eel_hole_hits', sa.Column('user_id', sa.String(), nullable=True, comment="The unique ID identifying a logged-in user's activity. Implemented 09-2025."))
    op.add_column('core_eel_hole_log_ins', sa.Column('user_id', sa.String(), nullable=True, comment="The unique ID identifying a logged-in user's activity. Implemented 09-2025."))
    op.add_column('core_eel_hole_previews', sa.Column('user_id', sa.String(), nullable=True, comment="The unique ID identifying a logged-in user's activity. Implemented 09-2025."))
    op.add_column('core_eel_hole_searches', sa.Column('user_id', sa.String(), nullable=True, comment="The unique ID identifying a logged-in user's activity. Implemented 09-2025."))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_eel_hole_searches', 'user_id')
    op.drop_column('core_eel_hole_previews', 'user_id')
    op.drop_column('core_eel_hole_log_ins', 'user_id')
    op.drop_column('core_eel_hole_hits', 'user_id')
    op.drop_column('core_eel_hole_downloads', 'user_id')
    op.drop_table('core_eel_hole_user_settings_updates')
    # ### end Alembic commands ###
