name: nightly
on:
  - push
  - pull_request
#  - schedule:
#      - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Decode GCP Credentials
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'catalyst-bizops-credentials.json'
          encodedString: ${{ secrets.CATALYST_BIZOPS_CREDENTIALS }}

      - name: Install BizOps
        run: |
          pip install ./

      - name: Update Harvest Data
        env:
          HARVEST_ACCOUNT_ID: ${{ secrets.HARVEST_ACCOUNT_ID }}
          HARVEST_TOKEN: ${{ secrets.HARVEST_TOKEN }}
          AUTH: ${{ secrets.CATALYST_BIZOPS_CREDENTIALS }}
          CATALYST_BIZOPS_CREDENTIALS: ${{ steps.write_file.outputs.filePath }}
        run: |
          harvest_to_gspread.py time_entries
