name: save-github-metrics
on:
  schedule:
    # First and third Mondays at 8AM Ak
    - cron: "00 16 1-7,15-21 * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Decode GCP Credentials
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'catalyst-usage-metrics-credentials.json'
          encodedString: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Save Github Metrics
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.write_file.outputs.filePath }}
          
        run: |
          pip install ./
          save_github_metrics.py
